### GENERAL SETTINGS ###

# Site settings
# title: Bestbg
description: "We offer a wide range of WordPress services, including WordPress installation and maintenance, WordPress Speed optimization, WordPress site transfers and more."
baseurl: "" #important: start with /
url: "https://bestbg.com"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /blog/:title/
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

kramdown:
  input: GFM

colors: #in hex code if not noted else
  primary: "#4D9C2F" #"#F70031"
  primary_rgb: "77,156,47" #"0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #"#33004D"
  link: "#00a800" #"#428bca"
  link_hover: "#2d2d2d" #"#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"


### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: google-plus
    url: https://www.google.com/+Canexo_com
  - title: facebook
    url: https://www.facebook.com/canexo.web
  - title: twitter
    url: https://twitter.com/canexo_com


# Clients information. Shown on Home and About pages.
clients:
  - name: Clients Desk
    img: Clients-desk.png

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: ["README.markdown", "script", "vendor", "Gemfile", "Gemfile.lock", "Procfile", "Rakefile", "readme.md", "scss", "node_modules"]

# GEMS enabled (changed to plugins).
# plugins: 
# - jekyll-redirect-from
# - jekyll-sitemap

  # Include underscores derictive
  # include: [_redirects]
