[build]
  command = "jekyll build"
  publish = "_site"

[build.environment]
  JEKYLL_ENV = "production"

#####################
#  Redirect Rules   #
#####################
[[redirects]]
  # HTTP to HTTPS link
  from = "https://bestbg.netlify.com/*"
  to = "https://bestbg.com/:splat"
  status = 301
  force = true

# Headers #

[[headers]]
for = "/*"
[headers.values]
cache-control = "public,max-age=60"
X-Frame-Options = "sameorigin"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "no-referrer-when-downgrade"
Feature-Policy = "camera 'none'; geolocation 'none'; microphone 'none'"

[[headers]]
  # Override cache duration for assets with periods in the filename (i.e. static assets)
  for = "/*.*"
    [headers.values]
    cache-control = "public,max-age=360000"
