[build]
  command = "jekyll build"
  publish = "_site"

[build.environment]
  JEKYLL_ENV = "production"

#####################
#  Redirect Rules   #
#####################
[[redirects]]
  # HTTP to HTTPS link
  from = "https://bestbg.netlify.com/*"
  to = "https://bestbg.com/:splat"
  status = 301
  force = true

# Headers #

[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "sameorigin"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options: nosniff
